///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8AmendSalesOrder_PP recording.
    /// </summary>
    [TestModule("0749ea8f-1efc-4471-a50f-7ea7f42de941", ModuleType.Recording, 1)]
    public partial class K8AmendSalesOrder_PP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8AmendSalesOrder_PP instance = new K8AmendSalesOrder_PP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8AmendSalesOrder_PP()
        {
            Quantity = "2";
            AccNumber = "CD961";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8AmendSalesOrder_PP Instance
        {
            get { return instance; }
        }

#region Variables

        string _Quantity;

        /// <summary>
        /// Gets or sets the value of variable Quantity.
        /// </summary>
        [TestVariable("51cedafe-e5f2-4da9-b036-6246b0f0130f")]
        public string Quantity
        {
            get { return _Quantity; }
            set { _Quantity = value; }
        }

        string _AccNumber;

        /// <summary>
        /// Gets or sets the value of variable AccNumber.
        /// </summary>
        [TestVariable("e5f07f02-93fb-4ffb-ac68-a5b3a1650548")]
        public string AccNumber
        {
            get { return _AccNumber; }
            set { _AccNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Howdens History') on item 'Ql1054K8QA3BackOfficeUserView2.HowdensHistory'.", repo.Ql1054K8QA3BackOfficeUserView2.HowdensHistoryInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.Ql1054K8QA3BackOfficeUserView2.HowdensHistoryInfo, "Text", "Howdens History");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3BackOfficeUserView2.HowdensHistory' at 41;26.", repo.Ql1054K8QA3BackOfficeUserView2.HowdensHistoryInfo, new RecordItemIndex(1));
            repo.Ql1054K8QA3BackOfficeUserView2.HowdensHistory.Click("41;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3BackOfficeUserView2.PushButton'.", repo.Ql1054K8QA3BackOfficeUserView2.PushButtonInfo, new RecordItemIndex(2));
            Validate.Exists(repo.Ql1054K8QA3BackOfficeUserView2.PushButtonInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3BackOfficeUserView2.PushButton' at 11;9.", repo.Ql1054K8QA3BackOfficeUserView2.PushButtonInfo, new RecordItemIndex(3));
            repo.Ql1054K8QA3BackOfficeUserView2.PushButton.Click("11;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Filter.Between'.", repo.Filter.BetweenInfo, new RecordItemIndex(4));
            Validate.Exists(repo.Filter.BetweenInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Filter.Between' at 31;11.", repo.Filter.BetweenInfo, new RecordItemIndex(5));
            repo.Filter.Between.Click("31;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 't' with focus on 'Filter.Between'.", repo.Filter.BetweenInfo, new RecordItemIndex(6));
            repo.Filter.Between.PressKeys("t", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Filter.And'.", repo.Filter.AndInfo, new RecordItemIndex(7));
            Validate.Exists(repo.Filter.AndInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Filter.And' at 23;9.", repo.Filter.AndInfo, new RecordItemIndex(8));
            repo.Filter.And.Click("23;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 't' with focus on 'Filter.And'.", repo.Filter.AndInfo, new RecordItemIndex(9));
            repo.Filter.And.PressKeys("t", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Filter.Text'.", repo.Filter.TextInfo, new RecordItemIndex(10));
            Validate.Exists(repo.Filter.TextInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Filter.Text' at 36;7.", repo.Filter.TextInfo, new RecordItemIndex(11));
            repo.Filter.Text.Click("36;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AccNumber' with focus on 'Filter.Text'.", repo.Filter.TextInfo, new RecordItemIndex(12));
            repo.Filter.Text.PressKeys(AccNumber, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Filter.Text'.", repo.Filter.TextInfo, new RecordItemIndex(13));
            repo.Filter.Text.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='OK') on item 'Filter.ButtonOK'.", repo.Filter.ButtonOKInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.Filter.ButtonOKInfo, "Text", "OK");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Filter.ButtonOK' at 36;8.", repo.Filter.ButtonOKInfo, new RecordItemIndex(15));
            repo.Filter.ButtonOK.Click("36;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.RowRow'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.RowRowInfo, new RecordItemIndex(16));
            Validate.Exists(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.RowRowInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.RowRow' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.RowRowInfo, new RecordItemIndex(17));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.RowRow.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Open Sale...') on item 'Kclient.OpenSale'.", repo.Kclient.OpenSaleInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.Kclient.OpenSaleInfo, "Text", "Open Sale...");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Kclient.OpenSale' at 87;18.", repo.Kclient.OpenSaleInfo, new RecordItemIndex(19));
            repo.Kclient.OpenSale.Click("87;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(20));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrderProcessingCreditNoteCR.Quantity'.", repo.SalesOrderProcessingCreditNoteCR.QuantityInfo, new RecordItemIndex(21));
            Validate.Exists(repo.SalesOrderProcessingCreditNoteCR.QuantityInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SalesOrderProcessingCreditNoteCR.Quantity' at 48;10.", repo.SalesOrderProcessingCreditNoteCR.QuantityInfo, new RecordItemIndex(22));
            repo.SalesOrderProcessingCreditNoteCR.Quantity.DoubleClick("48;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Quantity' with focus on 'SalesOrderProcessingCreditNoteCR.Text1'.", repo.SalesOrderProcessingCreditNoteCR.Text1Info, new RecordItemIndex(23));
            repo.SalesOrderProcessingCreditNoteCR.Text1.PressKeys(Quantity, 100);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Success, "User", "Sales Order after Amendment", repo.SalesOrderProcessingCreditNoteCR.Self, false, new RecordItemIndex(24));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Save') on item 'SalesOrderProcessingCreditNoteCR.Save'.", repo.SalesOrderProcessingCreditNoteCR.SaveInfo, new RecordItemIndex(25));
            Validate.AttributeEqual(repo.SalesOrderProcessingCreditNoteCR.SaveInfo, "Text", "Save");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SalesOrderProcessingCreditNoteCR.Save' at 49;20.", repo.SalesOrderProcessingCreditNoteCR.SaveInfo, new RecordItemIndex(26));
            repo.SalesOrderProcessingCreditNoteCR.Save.Click("49;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='OK') on item 'ActionSalesOrderSL17707.ButtonOK'.", repo.ActionSalesOrderSL17707.ButtonOKInfo, new RecordItemIndex(27));
            Validate.AttributeEqual(repo.ActionSalesOrderSL17707.ButtonOKInfo, "Text", "OK");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ActionSalesOrderSL17707.ButtonOK' at 51;6.", repo.ActionSalesOrderSL17707.ButtonOKInfo, new RecordItemIndex(28));
            repo.ActionSalesOrderSL17707.ButtonOK.Click("51;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(29));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Exit') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, new RecordItemIndex(30));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, "Text", "Exit");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit' at 51;32.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, new RecordItemIndex(31));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit.Click("51;32");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
