///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8AmendQuotation_PP recording.
    /// </summary>
    [TestModule("1b2a0c43-2d69-4873-ae9f-a0f9abbb4375", ModuleType.Recording, 1)]
    public partial class K8AmendQuotation_PP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8AmendQuotation_PP instance = new K8AmendQuotation_PP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8AmendQuotation_PP()
        {
            AccNumber = "CD961";
            Quantity = "2";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8AmendQuotation_PP Instance
        {
            get { return instance; }
        }

#region Variables

        string _AccNumber;

        /// <summary>
        /// Gets or sets the value of variable AccNumber.
        /// </summary>
        [TestVariable("cb0e1b4f-1799-4709-b514-957c911ea7d8")]
        public string AccNumber
        {
            get { return _AccNumber; }
            set { _AccNumber = value; }
        }

        string _Quantity;

        /// <summary>
        /// Gets or sets the value of variable Quantity.
        /// </summary>
        [TestVariable("0a5f1692-cb8f-4981-bec0-886a1bdbc0cc")]
        public string Quantity
        {
            get { return _Quantity; }
            set { _Quantity = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Howdens History') on item 'Ql1054K8QA3BackOfficeUserView2.HowdensHistory'.", repo.Ql1054K8QA3BackOfficeUserView2.HowdensHistoryInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.Ql1054K8QA3BackOfficeUserView2.HowdensHistoryInfo, "Text", "Howdens History");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3BackOfficeUserView2.HowdensHistory' at 46;33.", repo.Ql1054K8QA3BackOfficeUserView2.HowdensHistoryInfo, new RecordItemIndex(1));
            repo.Ql1054K8QA3BackOfficeUserView2.HowdensHistory.Click("46;33");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3BackOfficeUserView2.PushButton1'.", repo.Ql1054K8QA3BackOfficeUserView2.PushButton1Info, new RecordItemIndex(2));
            Validate.Exists(repo.Ql1054K8QA3BackOfficeUserView2.PushButton1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3BackOfficeUserView2.PushButton1' at 13;15.", repo.Ql1054K8QA3BackOfficeUserView2.PushButton1Info, new RecordItemIndex(3));
            repo.Ql1054K8QA3BackOfficeUserView2.PushButton1.Click("13;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Filter.Between'.", repo.Filter.BetweenInfo, new RecordItemIndex(4));
            Validate.Exists(repo.Filter.BetweenInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Filter.Between' at 25;5.", repo.Filter.BetweenInfo, new RecordItemIndex(5));
            repo.Filter.Between.Click("25;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 't' with focus on 'Filter.Between'.", repo.Filter.BetweenInfo, new RecordItemIndex(6));
            repo.Filter.Between.PressKeys("t", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Filter.And'.", repo.Filter.AndInfo, new RecordItemIndex(7));
            Validate.Exists(repo.Filter.AndInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Filter.And' at 26;9.", repo.Filter.AndInfo, new RecordItemIndex(8));
            repo.Filter.And.Click("26;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 't' with focus on 'Filter.And'.", repo.Filter.AndInfo, new RecordItemIndex(9));
            repo.Filter.And.PressKeys("t", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Filter.Text'.", repo.Filter.TextInfo, new RecordItemIndex(10));
            Validate.Exists(repo.Filter.TextInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Filter.Text' at 41;7.", repo.Filter.TextInfo, new RecordItemIndex(11));
            repo.Filter.Text.Click("41;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AccNumber' with focus on 'Filter.Text'.", repo.Filter.TextInfo, new RecordItemIndex(12));
            repo.Filter.Text.PressKeys(AccNumber, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Filter.Text'.", repo.Filter.TextInfo, new RecordItemIndex(13));
            repo.Filter.Text.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='OK') on item 'Filter.ButtonOK'.", repo.Filter.ButtonOKInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.Filter.ButtonOKInfo, "Text", "OK");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Filter.ButtonOK' at 39;12.", repo.Filter.ButtonOKInfo, new RecordItemIndex(15));
            repo.Filter.ButtonOK.Click("39;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3BackOfficeUserView2.RowRow1'.", repo.Ql1054K8QA3BackOfficeUserView2.RowRow1Info, new RecordItemIndex(16));
            Validate.Exists(repo.Ql1054K8QA3BackOfficeUserView2.RowRow1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Ql1054K8QA3BackOfficeUserView2.RowRow1' at Center.", repo.Ql1054K8QA3BackOfficeUserView2.RowRow1Info, new RecordItemIndex(17));
            repo.Ql1054K8QA3BackOfficeUserView2.RowRow1.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Open Quote...') on item 'Kclient.OpenQuote'.", repo.Kclient.OpenQuoteInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.Kclient.OpenQuoteInfo, "Text", "Open Quote...");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Kclient.OpenQuote' at 52;3.", repo.Kclient.OpenQuoteInfo, new RecordItemIndex(19));
            repo.Kclient.OpenQuote.Click("52;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(20));
            Delay.Duration(5000, false);
            
            Report.Screenshot(ReportLevel.Success, "User", "Quotation Before Amendment", repo.SalesOrderProcessingCreditNoteCR.Self, false, new RecordItemIndex(21));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrderProcessingCreditNoteCR.Quantity'.", repo.SalesOrderProcessingCreditNoteCR.QuantityInfo, new RecordItemIndex(22));
            Validate.Exists(repo.SalesOrderProcessingCreditNoteCR.QuantityInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SalesOrderProcessingCreditNoteCR.Quantity' at 57;9.", repo.SalesOrderProcessingCreditNoteCR.QuantityInfo, new RecordItemIndex(23));
            repo.SalesOrderProcessingCreditNoteCR.Quantity.DoubleClick("57;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrder193892HJIlford.Text'.", repo.SalesOrder193892HJIlford.TextInfo, new RecordItemIndex(24));
            Validate.Exists(repo.SalesOrder193892HJIlford.TextInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Quantity' with focus on 'SalesOrder193892HJIlford.Text'.", repo.SalesOrder193892HJIlford.TextInfo, new RecordItemIndex(25));
            repo.SalesOrder193892HJIlford.Text.PressKeys(Quantity, 100);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Success, "User", "Quotation After Amendment", repo.SalesOrderProcessingCreditNoteCR.Self, false, new RecordItemIndex(26));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Save') on item 'SalesOrderProcessingCreditNoteCR.Save'.", repo.SalesOrderProcessingCreditNoteCR.SaveInfo, new RecordItemIndex(27));
            Validate.AttributeEqual(repo.SalesOrderProcessingCreditNoteCR.SaveInfo, "Text", "Save");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SalesOrderProcessingCreditNoteCR.Save' at 43;24.", repo.SalesOrderProcessingCreditNoteCR.SaveInfo, new RecordItemIndex(28));
            repo.SalesOrderProcessingCreditNoteCR.Save.Click("43;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='OK') on item 'ActionQuotationQT193923.ButtonOK'.", repo.ActionQuotationQT193923.ButtonOKInfo, new RecordItemIndex(29));
            Validate.AttributeEqual(repo.ActionQuotationQT193923.ButtonOKInfo, "Text", "OK");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ActionQuotationQT193923.ButtonOK' at 31;9.", repo.ActionQuotationQT193923.ButtonOKInfo, new RecordItemIndex(30));
            repo.ActionQuotationQT193923.ButtonOK.Click("31;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(31));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Exit') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, new RecordItemIndex(32));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, "Text", "Exit");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit' at 47;28.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, new RecordItemIndex(33));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit.Click("47;28");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(34));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
