///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8AmendAssociateRecord_PP recording.
    /// </summary>
    [TestModule("e1f59842-bcd2-48fc-864e-825a946470c4", ModuleType.Recording, 1)]
    public partial class K8AmendAssociateRecord_PP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8AmendAssociateRecord_PP instance = new K8AmendAssociateRecord_PP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8AmendAssociateRecord_PP()
        {
            Product_1 = "DCK5341";
            Product_2 = "DCK5343";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8AmendAssociateRecord_PP Instance
        {
            get { return instance; }
        }

#region Variables

        string _Product_1;

        /// <summary>
        /// Gets or sets the value of variable Product_1.
        /// </summary>
        [TestVariable("50d6b3d6-fba9-4eed-94a1-40918610fcb3")]
        public string Product_1
        {
            get { return _Product_1; }
            set { _Product_1 = value; }
        }

        string _Product_2;

        /// <summary>
        /// Gets or sets the value of variable Product_2.
        /// </summary>
        [TestVariable("172ae6b9-fced-4390-9c54-298ea6282fdf")]
        public string Product_2
        {
            get { return _Product_2; }
            set { _Product_2 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Central Master Files') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, "Text", "Central Master Files");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, new RecordItemIndex(1));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Product File') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, "Text", "Product File");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, new RecordItemIndex(3));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Associated Products') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AssociatedProducts'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AssociatedProductsInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AssociatedProductsInfo, "Text", "Associated Products");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AssociatedProducts' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AssociatedProductsInfo, new RecordItemIndex(5));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AssociatedProducts.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4Info, new RecordItemIndex(6));
            Validate.Exists(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4Info, new RecordItemIndex(7));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Product_1' with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4Info, new RecordItemIndex(8));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4.PressKeys(Product_1, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4Info, new RecordItemIndex(9));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='New Product') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.NewProduct'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.NewProductInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.NewProductInfo, "Text", "New Product");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.NewProduct' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.NewProductInfo, new RecordItemIndex(11));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.NewProduct.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NewAssociatedProductForProductDCK53.Text'.", repo.NewAssociatedProductForProductDCK53.TextInfo, new RecordItemIndex(12));
            Validate.Exists(repo.NewAssociatedProductForProductDCK53.TextInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewAssociatedProductForProductDCK53.Text' at Center.", repo.NewAssociatedProductForProductDCK53.TextInfo, new RecordItemIndex(13));
            repo.NewAssociatedProductForProductDCK53.Text.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Product_2' with focus on 'NewAssociatedProductForProductDCK53.Text'.", repo.NewAssociatedProductForProductDCK53.TextInfo, new RecordItemIndex(14));
            repo.NewAssociatedProductForProductDCK53.Text.PressKeys(Product_2, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'NewAssociatedProductForProductDCK53.Text'.", repo.NewAssociatedProductForProductDCK53.TextInfo, new RecordItemIndex(15));
            repo.NewAssociatedProductForProductDCK53.Text.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NewAssociatedProductForProductDCK53.Text1'.", repo.NewAssociatedProductForProductDCK53.Text1Info, new RecordItemIndex(16));
            Validate.Exists(repo.NewAssociatedProductForProductDCK53.Text1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'NewAssociatedProductForProductDCK53.Text1' at Center.", repo.NewAssociatedProductForProductDCK53.Text1Info, new RecordItemIndex(17));
            repo.NewAssociatedProductForProductDCK53.Text1.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'NewAssociatedProductForProductDCK53.Text1'.", repo.NewAssociatedProductForProductDCK53.Text1Info, new RecordItemIndex(18));
            repo.NewAssociatedProductForProductDCK53.Text1.PressKeys("1", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'NewAssociatedProductForProductDCK53.Text1'.", repo.NewAssociatedProductForProductDCK53.Text1Info, new RecordItemIndex(19));
            repo.NewAssociatedProductForProductDCK53.Text1.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='OK') on item 'NewAssociatedProductForProductDCK53.ButtonOK'.", repo.NewAssociatedProductForProductDCK53.ButtonOKInfo, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.NewAssociatedProductForProductDCK53.ButtonOKInfo, "Text", "OK");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewAssociatedProductForProductDCK53.ButtonOK' at Center.", repo.NewAssociatedProductForProductDCK53.ButtonOKInfo, new RecordItemIndex(21));
            repo.NewAssociatedProductForProductDCK53.ButtonOK.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(22));
            Delay.Duration(1000, false);
            
            Report.Screenshot(ReportLevel.Success, "User", "View Associate Products Mapping", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Self, false, new RecordItemIndex(23));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Save') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Save'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SaveInfo, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SaveInfo, "Text", "Save");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Save' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SaveInfo, new RecordItemIndex(25));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Save.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Exit') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, new RecordItemIndex(26));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, "Text", "Exit");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, new RecordItemIndex(27));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Product File') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, new RecordItemIndex(28));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, "Text", "Product File");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, new RecordItemIndex(29));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Central Master Files') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, new RecordItemIndex(30));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, "Text", "Central Master Files");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, new RecordItemIndex(31));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
