///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8CreateSupersedeRecord_PP recording.
    /// </summary>
    [TestModule("c6c05b69-cd30-4ef5-be9d-d05ffd7c2fbc", ModuleType.Recording, 1)]
    public partial class K8CreateSupersedeRecord_PP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8CreateSupersedeRecord_PP instance = new K8CreateSupersedeRecord_PP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8CreateSupersedeRecord_PP()
        {
            FromPart = "DCK5541";
            ToPart = "DCK5542";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8CreateSupersedeRecord_PP Instance
        {
            get { return instance; }
        }

#region Variables

        string _FromPart;

        /// <summary>
        /// Gets or sets the value of variable FromPart.
        /// </summary>
        [TestVariable("0f15977f-86ce-4965-b6ec-ecad7d09fa3f")]
        public string FromPart
        {
            get { return _FromPart; }
            set { _FromPart = value; }
        }

        string _ToPart;

        /// <summary>
        /// Gets or sets the value of variable ToPart.
        /// </summary>
        [TestVariable("687970ab-5d9f-42b9-b746-48d125a720a7")]
        public string ToPart
        {
            get { return _ToPart; }
            set { _ToPart = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Central Master Files') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, "Text", "Central Master Files");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, new RecordItemIndex(1));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Product File') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, "Text", "Product File");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, new RecordItemIndex(3));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Supersede Products') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SupersedeProducts'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SupersedeProductsInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SupersedeProductsInfo, "Text", "Supersede Products");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SupersedeProducts' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SupersedeProductsInfo, new RecordItemIndex(5));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SupersedeProducts.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(6));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='One-To-One') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.OneToOne'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.OneToOneInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.OneToOneInfo, "Text", "One-To-One");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.OneToOne' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.OneToOneInfo, new RecordItemIndex(8));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.OneToOne.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductCode'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductCodeInfo, new RecordItemIndex(9));
            Validate.Exists(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductCodeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductCode' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductCodeInfo, new RecordItemIndex(10));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductCode.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FromPart' with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text2'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text2Info, new RecordItemIndex(11));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text2.PressKeys(FromPart, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text2'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text2Info, new RecordItemIndex(12));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text2.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text3'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text3Info, new RecordItemIndex(13));
            Validate.Exists(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text3Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text3' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text3Info, new RecordItemIndex(14));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text3.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ToPart' with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text3'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text3Info, new RecordItemIndex(15));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text3.PressKeys(ToPart, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text3'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text3Info, new RecordItemIndex(16));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text3.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(17));
            Delay.Duration(1000, false);
            
            Report.Screenshot(ReportLevel.Success, "User", "View the supersede mapping", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Self, false, new RecordItemIndex(18));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Save') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Save'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SaveInfo, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SaveInfo, "Text", "Save");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Save' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SaveInfo, new RecordItemIndex(20));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Save.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(21));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Exit') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, "Text", "Exit");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, new RecordItemIndex(23));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(24));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Product File') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, new RecordItemIndex(25));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, "Text", "Product File");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, new RecordItemIndex(26));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Central Master Files') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, new RecordItemIndex(27));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, "Text", "Central Master Files");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, new RecordItemIndex(28));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
