///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace K8_UK_PP_Regression
{
    public partial class K8CreateSalesOrderLines_PP
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }


        public void SalesOrderLine1()
        {
        	if (Product_1.Equals("ZZG50")) {
        		Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Product_1 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Product_1);
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '50' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("50");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
        	}
        	else if (Product_1.Equals("ZZD39")) {
        		Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Product_1 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Product_1);
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '50' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("50");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
        	}
        	else {
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Product_1 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Product_1);
	            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowText' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow.CellQty' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow.CellQty1Info);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowRow.CellQty.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Qty_1 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Qty_1);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow.Price' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow.PriceInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowRow.Price.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Price_1 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Price_1);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow.DiscPercent' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow.DiscPercentInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowRow.DiscPercent.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Disc_1 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Disc_1);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow.Status' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow.StatusInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowRow.Status.Click();
	  //          Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.Status'.", repo.Ql1054K8QA3SalesOrderProcessingD.StatusInfo);
	  //          Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.StatusInfo);
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.Status'.", repo.Ql1054K8QA3SalesOrderProcessingD.StatusInfo);
	            Keyboard.Press("{Tab}");
        	}
        }

        public void SalesOrderLine2()
        {
        	if (Product_2.Equals("ZZG50")) {
        		Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Product_2 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Product_2);
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '50' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("50");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
        	}
        	else if (Product_2.Equals("ZZD39")) {
        		Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Product_2 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Product_2);
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '50' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("50");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
        	}
        	else {	
	        	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Product_2 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Product_2);
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow1.CellQty' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow1.CellQtyInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowRow1.CellQty.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Qty_2 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Qty_2);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow1.Price' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow1.PriceInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowRow1.Price.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Price_2 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Price_2);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow1.DiscPercent' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow1.DiscPercentInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowRow1.DiscPercent.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Disc_2 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Disc_2);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow1.Status' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow1.StatusInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowRow1.Status.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.Status'.", repo.Ql1054K8QA3SalesOrderProcessingD.StatusInfo);
	            Keyboard.Press("{Tab}");
        	}

        }

        public void SalesOrderLine3()
        {
        	if (Product_3.Equals("ZZG50")) {
        		Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Product_3 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Product_3);
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '50' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("50");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
        	}
        	else if (Product_3.Equals("ZZD39")) {
        		Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Product_3 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Product_3);
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '50' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("50");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
        	}
        	else {
	        	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Product_3 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Product_3);
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow2.CellQty' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow2.CellQtyInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowRow2.CellQty.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Qty_3 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Qty_3);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow2.Price' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow2.PriceInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowRow2.Price.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Price_3 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Price_3);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow2.DiscPercent' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow2.DiscPercentInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowRow2.DiscPercent.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Disc_3 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Disc_3);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow2.Status' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow2.StatusInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowRow2.Status.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3Sal2esOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            Keyboard.Press("{Tab}");
        	}

        }
        
        public void SalesOrderLine4()
        {

        	if (Product_4.Equals("ZZG50")) {
        		Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Product_4 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Product_4);
            	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
            	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '50' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("50");
            	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
        	}
        	else if (Product_4.Equals("ZZD39")) {
        		Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Product_4 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Product_4);
            	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
            	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '50' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("50");
            	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
        	}
        	else{
        		Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Product_4 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Product_4);
            	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
            	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow4.CellQty' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow4.CellQtyInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowRow4.CellQty.Click();
            	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Qty_4 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Qty_4);
            	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow4.Price' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow4.PriceInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowRow4.Price.Click();
            	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Price_4 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Price_4);
            	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow4.DiscPercent' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow4.DiscPercentInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowRow4.DiscPercent.Click();
            	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $Disc_4 with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys(Disc_4);
            	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow4.Status' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow4.StatusInfo);
            	repo.Ql1054K8QA3SalesOrderProcessingD.RowRow4.Status.Click();
               	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.Status'.", repo.Ql1054K8QA3SalesOrderProcessingD.StatusInfo);
            	Keyboard.Press("{Tab}");
        	}

        }


    }
}