///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8CreateSalesOrderLines_PP recording.
    /// </summary>
    [TestModule("45652a13-5b59-424a-83a1-386bac45b0f9", ModuleType.Recording, 1)]
    public partial class K8CreateSalesOrderLines_PP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8CreateSalesOrderLines_PP instance = new K8CreateSalesOrderLines_PP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8CreateSalesOrderLines_PP()
        {
            Product_1 = "{LShiftKey down}BFY{LShiftKey up}9256";
            Product_2 = "{LShiftKey down}SCM{LShiftKey up}4126";
            Product_3 = "{LShiftKey down}DIC{LShiftKey up}0770";
            Product_4 = "{LShiftKey down}ZZG{LShiftKey up}50";
            Qty_1 = "1";
            Price_1 = "686.71";
            Disc_1 = "5";
            Qty_2 = "1";
            Price_2 = "679.00";
            Disc_2 = "10";
            Qty_3 = "1";
            Price_3 = "65.11";
            Disc_3 = "20";
            Qty_4 = "yourtext";
            Price_4 = "yourtext";
            Disc_4 = "yourtext";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8CreateSalesOrderLines_PP Instance
        {
            get { return instance; }
        }

#region Variables

        string _Product_1;

        /// <summary>
        /// Gets or sets the value of variable Product_1.
        /// </summary>
        [TestVariable("badb2129-115d-42d5-b3ec-09b3cbe10eb4")]
        public string Product_1
        {
            get { return _Product_1; }
            set { _Product_1 = value; }
        }

        string _Product_2;

        /// <summary>
        /// Gets or sets the value of variable Product_2.
        /// </summary>
        [TestVariable("a5b7f21d-b667-454b-a9c2-aabb1358612f")]
        public string Product_2
        {
            get { return _Product_2; }
            set { _Product_2 = value; }
        }

        string _Product_3;

        /// <summary>
        /// Gets or sets the value of variable Product_3.
        /// </summary>
        [TestVariable("78117d90-72ab-4762-862f-1341a8847a85")]
        public string Product_3
        {
            get { return _Product_3; }
            set { _Product_3 = value; }
        }

        string _Product_4;

        /// <summary>
        /// Gets or sets the value of variable Product_4.
        /// </summary>
        [TestVariable("944682ca-7d16-41bb-868b-42fe89181ff5")]
        public string Product_4
        {
            get { return _Product_4; }
            set { _Product_4 = value; }
        }

        string _Qty_1;

        /// <summary>
        /// Gets or sets the value of variable Qty_1.
        /// </summary>
        [TestVariable("f5312a4f-e07f-4f3d-a5c1-240d887fbcde")]
        public string Qty_1
        {
            get { return _Qty_1; }
            set { _Qty_1 = value; }
        }

        string _Price_1;

        /// <summary>
        /// Gets or sets the value of variable Price_1.
        /// </summary>
        [TestVariable("9c5b70de-6442-49b1-9be5-02501b2a8a14")]
        public string Price_1
        {
            get { return _Price_1; }
            set { _Price_1 = value; }
        }

        string _Disc_1;

        /// <summary>
        /// Gets or sets the value of variable Disc_1.
        /// </summary>
        [TestVariable("3142cb53-40aa-40a9-81cf-11667f8f7730")]
        public string Disc_1
        {
            get { return _Disc_1; }
            set { _Disc_1 = value; }
        }

        string _Qty_2;

        /// <summary>
        /// Gets or sets the value of variable Qty_2.
        /// </summary>
        [TestVariable("1b0c242e-9e56-4f26-a4e2-6a3cc3b9fa65")]
        public string Qty_2
        {
            get { return _Qty_2; }
            set { _Qty_2 = value; }
        }

        string _Price_2;

        /// <summary>
        /// Gets or sets the value of variable Price_2.
        /// </summary>
        [TestVariable("130a3d60-da8e-463b-aedd-5c28a845cdc1")]
        public string Price_2
        {
            get { return _Price_2; }
            set { _Price_2 = value; }
        }

        string _Disc_2;

        /// <summary>
        /// Gets or sets the value of variable Disc_2.
        /// </summary>
        [TestVariable("5f53e638-64c1-4be9-846e-06d4e123afaf")]
        public string Disc_2
        {
            get { return _Disc_2; }
            set { _Disc_2 = value; }
        }

        string _Qty_3;

        /// <summary>
        /// Gets or sets the value of variable Qty_3.
        /// </summary>
        [TestVariable("660fb5cb-d6f7-4384-8113-1de23e3c8c73")]
        public string Qty_3
        {
            get { return _Qty_3; }
            set { _Qty_3 = value; }
        }

        string _Price_3;

        /// <summary>
        /// Gets or sets the value of variable Price_3.
        /// </summary>
        [TestVariable("b1f3b48d-35e5-4cb0-b66e-4fbf683c294d")]
        public string Price_3
        {
            get { return _Price_3; }
            set { _Price_3 = value; }
        }

        string _Disc_3;

        /// <summary>
        /// Gets or sets the value of variable Disc_3.
        /// </summary>
        [TestVariable("ee5d2aaf-fd58-4cb0-af6c-d813a8589607")]
        public string Disc_3
        {
            get { return _Disc_3; }
            set { _Disc_3 = value; }
        }

        string _Qty_4;

        /// <summary>
        /// Gets or sets the value of variable Qty_4.
        /// </summary>
        [TestVariable("394756a0-7058-442f-aacf-70930c0db760")]
        public string Qty_4
        {
            get { return _Qty_4; }
            set { _Qty_4 = value; }
        }

        string _Price_4;

        /// <summary>
        /// Gets or sets the value of variable Price_4.
        /// </summary>
        [TestVariable("c0489a5f-1f4c-44aa-a2a9-41cf90fc4ec6")]
        public string Price_4
        {
            get { return _Price_4; }
            set { _Price_4 = value; }
        }

        string _Disc_4;

        /// <summary>
        /// Gets or sets the value of variable Disc_4.
        /// </summary>
        [TestVariable("36fe2a07-b7cb-443b-89ff-60151aa1bbf2")]
        public string Disc_4
        {
            get { return _Disc_4; }
            set { _Disc_4 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Row_1.
        /// </summary>
        [TestVariable("5f38ffb6-4ecf-4081-9716-91076fe85434")]
        public string Row_1
        {
            get { return repo.Row_1; }
            set { repo.Row_1 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Row_2.
        /// </summary>
        [TestVariable("a6705a2f-9bcb-42b1-9e80-860f745cf56c")]
        public string Row_2
        {
            get { return repo.Row_2; }
            set { repo.Row_2 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Row_3.
        /// </summary>
        [TestVariable("32930b53-e2f4-4b8d-86dd-048ed3d0e180")]
        public string Row_3
        {
            get { return repo.Row_3; }
            set { repo.Row_3 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Row_4.
        /// </summary>
        [TestVariable("89272b96-7990-4c49-a8a6-99882faa617e")]
        public string Row_4
        {
            get { return repo.Row_4; }
            set { repo.Row_4 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // First Sales Order Line Item
            Report.Log(ReportLevel.Info, "Section", "First Sales Order Line Item", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.RowRow.ProductCode'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow.ProductCodeInfo, new RecordItemIndex(1));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.RowRow.ProductCodeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow.ProductCode' at 28;7.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow.ProductCodeInfo, new RecordItemIndex(2));
            repo.Ql1054K8QA3SalesOrderProcessingD.RowRow.ProductCode.Click("28;7");
            Delay.Milliseconds(200);
            
            SalesOrderLine1();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(4));
            Delay.Duration(500, false);
            
            // Second Sales Order Line Item
            Report.Log(ReportLevel.Info, "Section", "Second Sales Order Line Item", new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo, new RecordItemIndex(6));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowText' at 21;9.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo, new RecordItemIndex(7));
            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.Click("21;9");
            Delay.Milliseconds(200);
            
            SalesOrderLine2();
            Delay.Milliseconds(0);
            
            // Third Sales Order Line Item
            Report.Log(ReportLevel.Info, "Section", "Third Sales Order Line Item", new RecordItemIndex(9));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo, new RecordItemIndex(10));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowText' at 39;7.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo, new RecordItemIndex(11));
            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.Click("39;7");
            Delay.Milliseconds(200);
            
            SalesOrderLine3();
            Delay.Milliseconds(0);
            
            // Fourth Sales Order Line Item
            Report.Log(ReportLevel.Info, "Section", "Fourth Sales Order Line Item", new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo, new RecordItemIndex(14));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowText' at 28;5.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo, new RecordItemIndex(15));
            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.Click("28;5");
            Delay.Milliseconds(200);
            
            SalesOrderLine4();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
