///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8CreateQuotationHeader_PP recording.
    /// </summary>
    [TestModule("7dc8bb6b-a7d7-4b68-add0-b9175ca6bb60", ModuleType.Recording, 1)]
    public partial class K8CreateQuotationHeader_PP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8CreateQuotationHeader_PP instance = new K8CreateQuotationHeader_PP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8CreateQuotationHeader_PP()
        {
            AccountNo = "CD723";
            Contact = "2423";
            OrderCategory = "C";
            DeliveryMethod = "G";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8CreateQuotationHeader_PP Instance
        {
            get { return instance; }
        }

#region Variables

        string _AccountNo;

        /// <summary>
        /// Gets or sets the value of variable AccountNo.
        /// </summary>
        [TestVariable("35a36c3e-45a8-406e-b152-368d9d0e3de5")]
        public string AccountNo
        {
            get { return _AccountNo; }
            set { _AccountNo = value; }
        }

        string _Contact;

        /// <summary>
        /// Gets or sets the value of variable Contact.
        /// </summary>
        [TestVariable("58d88eae-45f7-4312-ade4-280c14b838ed")]
        public string Contact
        {
            get { return _Contact; }
            set { _Contact = value; }
        }

        string _OrderCategory;

        /// <summary>
        /// Gets or sets the value of variable OrderCategory.
        /// </summary>
        [TestVariable("42f5867e-542f-41cf-b73e-f30a093f065b")]
        public string OrderCategory
        {
            get { return _OrderCategory; }
            set { _OrderCategory = value; }
        }

        string _DeliveryMethod;

        /// <summary>
        /// Gets or sets the value of variable DeliveryMethod.
        /// </summary>
        [TestVariable("b89b8081-12f3-4e76-8a38-c8580b8b07e2")]
        public string DeliveryMethod
        {
            get { return _DeliveryMethod; }
            set { _DeliveryMethod = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumberInfo, new RecordItemIndex(0));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumberInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber' at 23;9.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumberInfo, new RecordItemIndex(1));
            repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber.DoubleClick("23;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'qt' with focus on 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumberInfo, new RecordItemIndex(2));
            repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber.PressKeys("qt", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber2'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber2Info, new RecordItemIndex(3));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber2Info);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber2'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber2Info, new RecordItemIndex(4));
            repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber2.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.AccountNo'.", repo.Ql1054K8QA3SalesOrderProcessingD.AccountNoInfo, new RecordItemIndex(5));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.AccountNoInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Ql1054K8QA3SalesOrderProcessingD.AccountNo' at 48;8.", repo.Ql1054K8QA3SalesOrderProcessingD.AccountNoInfo, new RecordItemIndex(6));
            repo.Ql1054K8QA3SalesOrderProcessingD.AccountNo.DoubleClick("48;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AccountNo' with focus on 'Ql1054K8QA3SalesOrderProcessingD.AccountNo'.", repo.Ql1054K8QA3SalesOrderProcessingD.AccountNoInfo, new RecordItemIndex(7));
            repo.Ql1054K8QA3SalesOrderProcessingD.AccountNo.PressKeys(AccountNo, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.Contact'.", repo.Ql1054K8QA3SalesOrderProcessingD.ContactInfo, new RecordItemIndex(8));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.ContactInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Ql1054K8QA3SalesOrderProcessingD.Contact' at 41;10.", repo.Ql1054K8QA3SalesOrderProcessingD.ContactInfo, new RecordItemIndex(9));
            repo.Ql1054K8QA3SalesOrderProcessingD.Contact.DoubleClick("41;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Contact' with focus on 'Ql1054K8QA3SalesOrderProcessingD.Contact'.", repo.Ql1054K8QA3SalesOrderProcessingD.ContactInfo, new RecordItemIndex(10));
            repo.Ql1054K8QA3SalesOrderProcessingD.Contact.PressKeys(Contact, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.Contact2'.", repo.Ql1054K8QA3SalesOrderProcessingD.Contact2Info, new RecordItemIndex(11));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.Contact2Info);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.Contact2'.", repo.Ql1054K8QA3SalesOrderProcessingD.Contact2Info, new RecordItemIndex(12));
            repo.Ql1054K8QA3SalesOrderProcessingD.Contact2.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.OrderCategory'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderCategoryInfo, new RecordItemIndex(13));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.OrderCategoryInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Ql1054K8QA3SalesOrderProcessingD.OrderCategory' at 36;14.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderCategoryInfo, new RecordItemIndex(14));
            repo.Ql1054K8QA3SalesOrderProcessingD.OrderCategory.DoubleClick("36;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$OrderCategory' with focus on 'Ql1054K8QA3SalesOrderProcessingD.OrderCategory'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderCategoryInfo, new RecordItemIndex(15));
            repo.Ql1054K8QA3SalesOrderProcessingD.OrderCategory.PressKeys(OrderCategory, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.OrderCategory'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderCategoryInfo, new RecordItemIndex(16));
            repo.Ql1054K8QA3SalesOrderProcessingD.OrderCategory.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            try {
                Validate_Text();
                Delay.Milliseconds(2000);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(17)); }
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.DeliveryMethod'.", repo.Ql1054K8QA3SalesOrderProcessingD.DeliveryMethodInfo, new RecordItemIndex(18));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.DeliveryMethodInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Ql1054K8QA3SalesOrderProcessingD.DeliveryMethod' at 36;10.", repo.Ql1054K8QA3SalesOrderProcessingD.DeliveryMethodInfo, new RecordItemIndex(19));
            repo.Ql1054K8QA3SalesOrderProcessingD.DeliveryMethod.DoubleClick("36;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$DeliveryMethod' with focus on 'Ql1054K8QA3SalesOrderProcessingD.DeliveryMethod'.", repo.Ql1054K8QA3SalesOrderProcessingD.DeliveryMethodInfo, new RecordItemIndex(20));
            repo.Ql1054K8QA3SalesOrderProcessingD.DeliveryMethod.PressKeys(DeliveryMethod, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(21));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
