///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8DeleteAssociateRecord_PP recording.
    /// </summary>
    [TestModule("5725dcb0-c735-42a2-a6ea-43bb75a5601b", ModuleType.Recording, 1)]
    public partial class K8DeleteAssociateRecord_PP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8DeleteAssociateRecord_PP instance = new K8DeleteAssociateRecord_PP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8DeleteAssociateRecord_PP()
        {
            Product_1 = "DCK5341";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8DeleteAssociateRecord_PP Instance
        {
            get { return instance; }
        }

#region Variables

        string _Product_1;

        /// <summary>
        /// Gets or sets the value of variable Product_1.
        /// </summary>
        [TestVariable("3549e6c1-eb09-438b-a286-f826ba15af54")]
        public string Product_1
        {
            get { return _Product_1; }
            set { _Product_1 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Central Master Files') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, "Text", "Central Master Files");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, new RecordItemIndex(1));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Product File') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, "Text", "Product File");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, new RecordItemIndex(3));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Associated Products') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AssociatedProducts'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AssociatedProductsInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AssociatedProductsInfo, "Text", "Associated Products");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AssociatedProducts' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AssociatedProductsInfo, new RecordItemIndex(5));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AssociatedProducts.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4Info, new RecordItemIndex(6));
            Validate.Exists(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4Info, new RecordItemIndex(7));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Product_1' with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4Info, new RecordItemIndex(8));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4.PressKeys(Product_1, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4Info, new RecordItemIndex(9));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text4.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Delete') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Delete'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.DeleteInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.DeleteInfo, "Text", "Delete");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Delete' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.DeleteInfo, new RecordItemIndex(11));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Delete.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(12));
            Delay.Duration(1000, false);
            
            Report.Screenshot(ReportLevel.Success, "User", "View Associate Products Mapping", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Self, false, new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'DeleteCurrentRow.ButtonYes'.", repo.DeleteCurrentRow.ButtonYesInfo, new RecordItemIndex(14));
            Validate.Exists(repo.DeleteCurrentRow.ButtonYesInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeleteCurrentRow.ButtonYes' at Center.", repo.DeleteCurrentRow.ButtonYesInfo, new RecordItemIndex(15));
            repo.DeleteCurrentRow.ButtonYes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Exit') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, "Text", "Exit");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, new RecordItemIndex(17));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Product File') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, "Text", "Product File");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFileInfo, new RecordItemIndex(19));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ProductFile.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Central Master Files') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, "Text", "Central Master Files");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, new RecordItemIndex(21));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
