///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace K8_UK_PP_Regression
{
    public partial class K8GetSalesOrderInfo2_PP
    {

        private void Init()
        {
        }

        public void setSAPSalesInvoice(string Depot)
        {
        	string inv = Depot + SalesInvoiceNumber.Substring(1,7);
       		SAPSalesInvoice = inv;
        }

        public void WriteToTextFile(string fileNameWithPath, string contents)
        {
        	string message = "";
            if (!string.IsNullOrEmpty(fileNameWithPath))
            {
                try
                {
                    using (System.IO.StreamWriter sw = new System.IO.StreamWriter(fileNameWithPath, true))
                    {
                        sw.WriteLine(contents);
                    }
                }
                catch (Exception e)
                {
                    message = "Unable to write log message (" + message + ") due to exception: " + e.Message;
                }
            }
            else
            {
                message = "No file name provided for logging";
            }
        }

        public void SetDate()
        {
        	string date = System.DateTime.Today.ToString("dd.MM.yyyy");
        	TodayDate = date;
        }

        public void OutputData()
        {
            OpenXML.CopyValueToExcel(excelFileLocation, SAPSalesInvoice, "A", 2);
            OpenXML.CopyValueToExcel(excelFileLocation, Goods, "B", 2);
            OpenXML.CopyValueToExcel(excelFileLocation, VAT, "C", 2);
        }

    }
}
