///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8GetAmendedOrderInfo_PP recording.
    /// </summary>
    [TestModule("7330b0c4-509b-4446-b18b-1a6a79ae8aea", ModuleType.Recording, 1)]
    public partial class K8GetAmendedOrderInfo_PP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8GetAmendedOrderInfo_PP instance = new K8GetAmendedOrderInfo_PP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8GetAmendedOrderInfo_PP()
        {
            RefundOrderNumber = "";
            FilePath = "C:\\Temp\\SalesOrderInfoUK.txt";
            Login = "";
            Account = "";
            RefundInvoice = "";
            Depot = "";
            excelFileLocation = "";
            SAPReturnsInvoice = "";
            RefundGoods = "";
            RefundVAT = "";
            SalesInvoiceNumber = "";
            SalesOrderNumber = "";
            TodayDate = "";
            SalesOrderNum = "";
            TestName = "";
            SAPSalesInvoice = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8GetAmendedOrderInfo_PP Instance
        {
            get { return instance; }
        }

#region Variables

        string _RefundOrderNumber;

        /// <summary>
        /// Gets or sets the value of variable RefundOrderNumber.
        /// </summary>
        [TestVariable("57709a28-7791-40a7-b4c8-7623ad35c1f5")]
        public string RefundOrderNumber
        {
            get { return _RefundOrderNumber; }
            set { _RefundOrderNumber = value; }
        }

        string _FilePath;

        /// <summary>
        /// Gets or sets the value of variable FilePath.
        /// </summary>
        [TestVariable("ee8fd62c-746f-4754-81af-2cf1efd2d2f0")]
        public string FilePath
        {
            get { return _FilePath; }
            set { _FilePath = value; }
        }

        string _Login;

        /// <summary>
        /// Gets or sets the value of variable Login.
        /// </summary>
        [TestVariable("dfa28cd3-b232-4c00-b71e-796cf6cfc492")]
        public string Login
        {
            get { return _Login; }
            set { _Login = value; }
        }

        string _Account;

        /// <summary>
        /// Gets or sets the value of variable Account.
        /// </summary>
        [TestVariable("91c684ae-6fda-45f9-94a7-38ee812a0f4c")]
        public string Account
        {
            get { return _Account; }
            set { _Account = value; }
        }

        string _RefundInvoice;

        /// <summary>
        /// Gets or sets the value of variable RefundInvoice.
        /// </summary>
        [TestVariable("930d3fe4-a626-4bb7-b6ca-048be4eb4190")]
        public string RefundInvoice
        {
            get { return _RefundInvoice; }
            set { _RefundInvoice = value; }
        }

        string _Depot;

        /// <summary>
        /// Gets or sets the value of variable Depot.
        /// </summary>
        [TestVariable("4251f089-6e7e-4824-80d2-a0a48ad2034b")]
        public string Depot
        {
            get { return _Depot; }
            set { _Depot = value; }
        }

        string _excelFileLocation;

        /// <summary>
        /// Gets or sets the value of variable excelFileLocation.
        /// </summary>
        [TestVariable("a123c879-ef1b-4503-82dd-eb3419f8c422")]
        public string excelFileLocation
        {
            get { return _excelFileLocation; }
            set { _excelFileLocation = value; }
        }

        string _SAPReturnsInvoice;

        /// <summary>
        /// Gets or sets the value of variable SAPReturnsInvoice.
        /// </summary>
        [TestVariable("95a9f1ff-f3a5-4dd1-afd7-cb27ef076b47")]
        public string SAPReturnsInvoice
        {
            get { return _SAPReturnsInvoice; }
            set { _SAPReturnsInvoice = value; }
        }

        string _RefundGoods;

        /// <summary>
        /// Gets or sets the value of variable RefundGoods.
        /// </summary>
        [TestVariable("fc17d726-54cf-4dad-b5b0-447c52a574f0")]
        public string RefundGoods
        {
            get { return _RefundGoods; }
            set { _RefundGoods = value; }
        }

        string _RefundVAT;

        /// <summary>
        /// Gets or sets the value of variable RefundVAT.
        /// </summary>
        [TestVariable("d52f348b-48ba-4b6a-a800-b9c0e6d97e12")]
        public string RefundVAT
        {
            get { return _RefundVAT; }
            set { _RefundVAT = value; }
        }

        string _SalesInvoiceNumber;

        /// <summary>
        /// Gets or sets the value of variable SalesInvoiceNumber.
        /// </summary>
        [TestVariable("05cbb7f7-3171-4862-bdf8-88b5e0da4211")]
        public string SalesInvoiceNumber
        {
            get { return _SalesInvoiceNumber; }
            set { _SalesInvoiceNumber = value; }
        }

        string _SalesOrderNumber;

        /// <summary>
        /// Gets or sets the value of variable SalesOrderNumber.
        /// </summary>
        [TestVariable("7624f75f-e647-402f-9e3c-bd31d32efa5b")]
        public string SalesOrderNumber
        {
            get { return _SalesOrderNumber; }
            set { _SalesOrderNumber = value; }
        }

        string _TodayDate;

        /// <summary>
        /// Gets or sets the value of variable TodayDate.
        /// </summary>
        [TestVariable("55eb826f-0cd1-4307-804b-478c03cf9a97")]
        public string TodayDate
        {
            get { return _TodayDate; }
            set { _TodayDate = value; }
        }

        string _SalesOrderNum;

        /// <summary>
        /// Gets or sets the value of variable SalesOrderNum.
        /// </summary>
        [TestVariable("57e567fe-2edb-496a-bbe3-c79d29ef19cc")]
        public string SalesOrderNum
        {
            get { return _SalesOrderNum; }
            set { _SalesOrderNum = value; }
        }

        string _TestName;

        /// <summary>
        /// Gets or sets the value of variable TestName.
        /// </summary>
        [TestVariable("67d6de64-f807-4253-9280-acbd9a60fc55")]
        public string TestName
        {
            get { return _TestName; }
            set { _TestName = value; }
        }

        string _SAPSalesInvoice;

        /// <summary>
        /// Gets or sets the value of variable SAPSalesInvoice.
        /// </summary>
        [TestVariable("5f1bf688-5bd1-4212-ab4c-397de78820eb")]
        public string SAPSalesInvoice
        {
            get { return _SAPSalesInvoice; }
            set { _SAPSalesInvoice = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            SetDate();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumberInfo, new RecordItemIndex(1));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumberInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber' at 27;10.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumberInfo, new RecordItemIndex(2));
            repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber.DoubleClick("27;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'L' with focus on 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumberInfo, new RecordItemIndex(3));
            repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber.PressKeys("L", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber2'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber2Info, new RecordItemIndex(4));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber2Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber2'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber2Info, new RecordItemIndex(5));
            repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber2.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.Display'.", repo.Ql1054K8QA3SalesOrderProcessingD.DisplayInfo, new RecordItemIndex(6));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.DisplayInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.Display' at 24;9.", repo.Ql1054K8QA3SalesOrderProcessingD.DisplayInfo, new RecordItemIndex(7));
            repo.Ql1054K8QA3SalesOrderProcessingD.Display.Click("24;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Kclient.DisplaySalesOrderHistory' at 63;8.", repo.Kclient.DisplaySalesOrderHistoryInfo, new RecordItemIndex(8));
            repo.Kclient.DisplaySalesOrderHistory.Click("63;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrderHistory.OrderNumber'.", repo.SalesOrderHistory.OrderNumberInfo, new RecordItemIndex(9));
            Validate.Exists(repo.SalesOrderHistory.OrderNumberInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'SalesOrderHistory.OrderNumber' and assigning its value to variable 'SalesOrderNum'.", repo.SalesOrderHistory.OrderNumberInfo, new RecordItemIndex(10));
            SalesOrderNum = repo.SalesOrderHistory.OrderNumber.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", SalesOrderNum, new RecordItemIndex(11));
            
            WriteToTextFile(FilePath, "=============================================");
            Delay.Milliseconds(0);
            
            WriteToTextFile(FilePath, TestName);
            Delay.Milliseconds(0);
            
            WriteToTextFile(FilePath, TodayDate);
            Delay.Milliseconds(0);
            
            WriteToTextFile(FilePath, "=============================================");
            Delay.Milliseconds(0);
            
            WriteToTextFile(FilePath, SalesOrderNum);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SalesOrderHistory.RowRow1.Cell62116' at 18;8.", repo.SalesOrderHistory.RowRow1.Cell62116Info, new RecordItemIndex(17));
            repo.SalesOrderHistory.RowRow1.Cell62116.Click("18;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrderHistory.RowRow1.D723manager'.", repo.SalesOrderHistory.RowRow1.D723managerInfo, new RecordItemIndex(18));
            Validate.Exists(repo.SalesOrderHistory.RowRow1.D723managerInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'AccessibleName' from item 'SalesOrderHistory.RowRow1.D723manager' and assigning its value to variable 'Login'.", repo.SalesOrderHistory.RowRow1.D723managerInfo, new RecordItemIndex(19));
            Login = repo.SalesOrderHistory.RowRow1.D723manager.Element.GetAttributeValueText("AccessibleName");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Login, new RecordItemIndex(20));
            
            WriteToTextFile(FilePath, Login);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrderHistory.RowRow1.CD723'.", repo.SalesOrderHistory.RowRow1.CD723Info, new RecordItemIndex(22));
            Validate.Exists(repo.SalesOrderHistory.RowRow1.CD723Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'AccessibleName' from item 'SalesOrderHistory.RowRow1.CD723' and assigning its value to variable 'Account'.", repo.SalesOrderHistory.RowRow1.CD723Info, new RecordItemIndex(23));
            Account = repo.SalesOrderHistory.RowRow1.CD723.Element.GetAttributeValueText("AccessibleName");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Account, new RecordItemIndex(24));
            
            WriteToTextFile(FilePath, Account);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrderHistory.RowRow1.Cell00010968'.", repo.SalesOrderHistory.RowRow1.Cell00010968Info, new RecordItemIndex(26));
            Validate.Exists(repo.SalesOrderHistory.RowRow1.Cell00010968Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'AccessibleName' from item 'SalesOrderHistory.RowRow1.Cell00010968' and assigning its value to variable 'SalesInvoiceNumber'.", repo.SalesOrderHistory.RowRow1.Cell00010968Info, new RecordItemIndex(27));
            SalesInvoiceNumber = repo.SalesOrderHistory.RowRow1.Cell00010968.Element.GetAttributeValueText("AccessibleName");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", SalesInvoiceNumber, new RecordItemIndex(28));
            
            WriteToTextFile(FilePath, SalesInvoiceNumber);
            Delay.Milliseconds(0);
            
            setSAPSalesInvoice(Depot);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrderHistory.RowRow1.Cell6511'.", repo.SalesOrderHistory.RowRow1.Cell6511Info, new RecordItemIndex(31));
            Validate.Exists(repo.SalesOrderHistory.RowRow1.Cell6511Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'AccessibleName' from item 'SalesOrderHistory.RowRow1.Cell6511' and assigning its value to variable 'RefundGoods'.", repo.SalesOrderHistory.RowRow1.Cell6511Info, new RecordItemIndex(32));
            RefundGoods = repo.SalesOrderHistory.RowRow1.Cell6511.Element.GetAttributeValueText("AccessibleName");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", RefundGoods, new RecordItemIndex(33));
            
            WriteToTextFile(FilePath, RefundGoods);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrderHistory.RowRow1.Cell1302'.", repo.SalesOrderHistory.RowRow1.Cell1302Info, new RecordItemIndex(35));
            Validate.Exists(repo.SalesOrderHistory.RowRow1.Cell1302Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'AccessibleName' from item 'SalesOrderHistory.RowRow1.Cell1302' and assigning its value to variable 'RefundVAT'.", repo.SalesOrderHistory.RowRow1.Cell1302Info, new RecordItemIndex(36));
            RefundVAT = repo.SalesOrderHistory.RowRow1.Cell1302.Element.GetAttributeValueText("AccessibleName");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", RefundVAT, new RecordItemIndex(37));
            
            WriteToTextFile(FilePath, RefundVAT);
            Delay.Milliseconds(0);
            
            WriteToTextFile(FilePath, "---------------------------------------------");
            Delay.Milliseconds(0);
            
            WriteToTextFile(FilePath, "");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrder193931HJIlford.ButtonOK'.", repo.SalesOrder193931HJIlford.ButtonOKInfo, new RecordItemIndex(41));
            Validate.Exists(repo.SalesOrder193931HJIlford.ButtonOKInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SalesOrder193931HJIlford.ButtonOK' at 40;10.", repo.SalesOrder193931HJIlford.ButtonOKInfo, new RecordItemIndex(42));
            repo.SalesOrder193931HJIlford.ButtonOK.Click("40;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.Process'.", repo.Ql1054K8QA3SalesOrderProcessingD.ProcessInfo, new RecordItemIndex(43));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.ProcessInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.Process' at 53;18.", repo.Ql1054K8QA3SalesOrderProcessingD.ProcessInfo, new RecordItemIndex(44));
            repo.Ql1054K8QA3SalesOrderProcessingD.Process.Click("53;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ActionSalesOrderSL17707.ButtonOK'.", repo.ActionSalesOrderSL17707.ButtonOKInfo, new RecordItemIndex(45));
            Validate.Exists(repo.ActionSalesOrderSL17707.ButtonOKInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ActionSalesOrderSL17707.ButtonOK' at 29;7.", repo.ActionSalesOrderSL17707.ButtonOKInfo, new RecordItemIndex(46));
            repo.ActionSalesOrderSL17707.ButtonOK.Click("29;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(47));
            Delay.Duration(5000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
