///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace K8_UK_PP_Regression
{
    public partial class K8GetRefundOrderInfo_PP
    {

        private void Init()
        {
        }
        
        public void WriteToTextFileRefund(string fileNameWithPath, string contents)
        {
        	string message = "";
            if (!string.IsNullOrEmpty(fileNameWithPath))
            {
                try
                {
                    using (System.IO.StreamWriter sw = new System.IO.StreamWriter(fileNameWithPath, true))
                    {
                        sw.WriteLine(contents);
                    }
                }
                catch (Exception e)
                {
                    message = "Unable to write log message (" + message + ") due to exception: " + e.Message;
                }
            }
            else
            {
                message = "No file name provided for logging";
            }

        }
                
        public void setSAPReturnsInvoice(string Depot)
        {
        	string retInv = Depot + RefundInvoice.Substring(1,7);
        	SAPReturnsInvoice = retInv;
        	
        	OpenXML.CopyValueToExcel(excelFileLocation, SAPReturnsInvoice, "D", 2);
        }

    }
}