///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8InvokePurchaseOrder_PP recording.
    /// </summary>
    [TestModule("373ef2a7-6e43-4787-af1b-11bb5331e523", ModuleType.Recording, 1)]
    public partial class K8InvokePurchaseOrder_PP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8InvokePurchaseOrder_PP instance = new K8InvokePurchaseOrder_PP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8InvokePurchaseOrder_PP()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8InvokePurchaseOrder_PP Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Purchase Control') on item 'Ql1054K8QA3BackOfficeUserView2.Outline1.PurchaseControl'.", repo.Ql1054K8QA3BackOfficeUserView2.Outline1.PurchaseControlInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.Ql1054K8QA3BackOfficeUserView2.Outline1.PurchaseControlInfo, "Text", "Purchase Control");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3BackOfficeUserView2.Outline1.PurchaseControl' at Center.", repo.Ql1054K8QA3BackOfficeUserView2.Outline1.PurchaseControlInfo, new RecordItemIndex(1));
            repo.Ql1054K8QA3BackOfficeUserView2.Outline1.PurchaseControl.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(2));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Purchase Order') on item 'Ql1054K8QA3BackOfficeUserView2.Outline1.PurchaseOrder'.", repo.Ql1054K8QA3BackOfficeUserView2.Outline1.PurchaseOrderInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.Ql1054K8QA3BackOfficeUserView2.Outline1.PurchaseOrderInfo, "Text", "Purchase Order");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3BackOfficeUserView2.Outline1.PurchaseOrder' at Center.", repo.Ql1054K8QA3BackOfficeUserView2.Outline1.PurchaseOrderInfo, new RecordItemIndex(4));
            repo.Ql1054K8QA3BackOfficeUserView2.Outline1.PurchaseOrder.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(5));
            Delay.Duration(5000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
