///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8MakeCustomerAmendment recording.
    /// </summary>
    [TestModule("d5e9fb49-040e-4f4c-b3a4-dc9c84d19d69", ModuleType.Recording, 1)]
    public partial class K8MakeCustomerAmendment : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8MakeCustomerAmendment instance = new K8MakeCustomerAmendment();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8MakeCustomerAmendment()
        {
            Amendment = "1000017340";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8MakeCustomerAmendment Instance
        {
            get { return instance; }
        }

#region Variables

        string _Amendment;

        /// <summary>
        /// Gets or sets the value of variable Amendment.
        /// </summary>
        [TestVariable("4cff9b7f-b1fc-4696-857b-49a50e741f16")]
        public string Amendment
        {
            get { return _Amendment; }
            set { _Amendment = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Central Master Files') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, "Text", "Central Master Files");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFilesInfo, new RecordItemIndex(1));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CentralMasterFiles.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Customer File') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CustomerFile'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CustomerFileInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CustomerFileInfo, "Text", "Customer File");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CustomerFile' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CustomerFileInfo, new RecordItemIndex(3));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CustomerFile.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Customer Maintenance') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CustomerMaintenance'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CustomerMaintenanceInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CustomerMaintenanceInfo, "Text", "Customer Maintenance");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CustomerMaintenance' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CustomerMaintenanceInfo, new RecordItemIndex(5));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.CustomerMaintenance.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(6));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text5'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text5Info, new RecordItemIndex(7));
            Validate.Exists(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text5Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text5' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text5Info, new RecordItemIndex(8));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text5.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Amendment' with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text5'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text5Info, new RecordItemIndex(9));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text5.PressKeys(Amendment, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text5'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text5Info, new RecordItemIndex(10));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text5.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(11));
            Delay.Duration(3000, false);
            
            Report.Screenshot(ReportLevel.Success, "User", "Before Customer Amendment", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Self, false, new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Amend') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Amend'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AmendInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AmendInfo, "Text", "Amend");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Amend' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.AmendInfo, new RecordItemIndex(14));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Amend.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(15));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text6'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text6Info, new RecordItemIndex(16));
            Validate.Exists(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text6Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text6' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text6Info, new RecordItemIndex(17));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text6.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Space}Amendment' with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text6'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text6Info, new RecordItemIndex(18));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text6.PressKeys("{Space}Amendment", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text6'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text6Info, new RecordItemIndex(19));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text6.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(20));
            Delay.Duration(3000, false);
            
            Report.Screenshot(ReportLevel.Success, "User", "After Customer Amendment", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Self, false, new RecordItemIndex(21));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Save') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Save'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SaveInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SaveInfo, "Text", "Save");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Save' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.SaveInfo, new RecordItemIndex(23));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Save.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(24));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
