///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8MakeCashAdjustmentPP recording.
    /// </summary>
    [TestModule("8c2eb278-1a47-4d63-a917-76a46c01bc42", ModuleType.Recording, 1)]
    public partial class K8MakeCashAdjustmentPP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8MakeCashAdjustmentPP instance = new K8MakeCashAdjustmentPP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8MakeCashAdjustmentPP()
        {
            TillNumber = "1";
            CashType = "C";
            ReasonCode = "26";
            Text = "Test";
            Total = "5";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8MakeCashAdjustmentPP Instance
        {
            get { return instance; }
        }

#region Variables

        string _TillNumber;

        /// <summary>
        /// Gets or sets the value of variable TillNumber.
        /// </summary>
        [TestVariable("d0b389f1-6ea7-416f-91ab-2870a0e7d817")]
        public string TillNumber
        {
            get { return _TillNumber; }
            set { _TillNumber = value; }
        }

        string _CashType;

        /// <summary>
        /// Gets or sets the value of variable CashType.
        /// </summary>
        [TestVariable("159d5230-8615-49b1-987c-af74521c2586")]
        public string CashType
        {
            get { return _CashType; }
            set { _CashType = value; }
        }

        string _ReasonCode;

        /// <summary>
        /// Gets or sets the value of variable ReasonCode.
        /// </summary>
        [TestVariable("a96aaaed-3966-4bb1-9579-cb1879459c05")]
        public string ReasonCode
        {
            get { return _ReasonCode; }
            set { _ReasonCode = value; }
        }

        string _Text;

        /// <summary>
        /// Gets or sets the value of variable Text.
        /// </summary>
        [TestVariable("97f507c0-b52c-47fa-b5ef-cc7fff5a1ab8")]
        public string Text
        {
            get { return _Text; }
            set { _Text = value; }
        }

        string _Total;

        /// <summary>
        /// Gets or sets the value of variable Total.
        /// </summary>
        [TestVariable("65bf33c3-4083-4ecc-aed3-d3eda999f6b4")]
        public string Total
        {
            get { return _Total; }
            set { _Total = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.Tools'.", repo.Ql1054K8QA3SalesOrderProcessingD.ToolsInfo, new RecordItemIndex(0));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.ToolsInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.Tools' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.ToolsInfo, new RecordItemIndex(1));
            repo.Ql1054K8QA3SalesOrderProcessingD.Tools.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Kclient.OpenCashDrawer' at 65;9.", repo.Kclient.OpenCashDrawerInfo, new RecordItemIndex(2));
            repo.Kclient.OpenCashDrawer.Click("65;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Cash_Adjustments.CurrentTillNumber'.", repo.Cash_Adjustments.CurrentTillNumberInfo, new RecordItemIndex(3));
            Validate.Exists(repo.Cash_Adjustments.CurrentTillNumberInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Cash_Adjustments.CurrentTillNumber' at 28;9.", repo.Cash_Adjustments.CurrentTillNumberInfo, new RecordItemIndex(4));
            repo.Cash_Adjustments.CurrentTillNumber.DoubleClick("28;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TillNumber' with focus on 'Cash_Adjustments.CurrentTillNumber'.", repo.Cash_Adjustments.CurrentTillNumberInfo, new RecordItemIndex(5));
            repo.Cash_Adjustments.CurrentTillNumber.PressKeys(TillNumber, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Cash_Adjustments.AdjustmentCashType'.", repo.Cash_Adjustments.AdjustmentCashTypeInfo, new RecordItemIndex(6));
            Validate.Exists(repo.Cash_Adjustments.AdjustmentCashTypeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Cash_Adjustments.AdjustmentCashType' at 35;9.", repo.Cash_Adjustments.AdjustmentCashTypeInfo, new RecordItemIndex(7));
            repo.Cash_Adjustments.AdjustmentCashType.DoubleClick("35;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CashType' with focus on 'Cash_Adjustments.AdjustmentCashType'.", repo.Cash_Adjustments.AdjustmentCashTypeInfo, new RecordItemIndex(8));
            repo.Cash_Adjustments.AdjustmentCashType.PressKeys(CashType, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Cash_Adjustments.ReasonCode'.", repo.Cash_Adjustments.ReasonCodeInfo, new RecordItemIndex(9));
            Validate.Exists(repo.Cash_Adjustments.ReasonCodeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Cash_Adjustments.ReasonCode' at 62;9.", repo.Cash_Adjustments.ReasonCodeInfo, new RecordItemIndex(10));
            repo.Cash_Adjustments.ReasonCode.Click("62;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ReasonCode' with focus on 'Cash_Adjustments.ReasonCode'.", repo.Cash_Adjustments.ReasonCodeInfo, new RecordItemIndex(11));
            repo.Cash_Adjustments.ReasonCode.PressKeys(ReasonCode, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Cash_Adjustments.Text'.", repo.Cash_Adjustments.TextInfo, new RecordItemIndex(12));
            Validate.Exists(repo.Cash_Adjustments.TextInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Cash_Adjustments.Text' at 72;28.", repo.Cash_Adjustments.TextInfo, new RecordItemIndex(13));
            repo.Cash_Adjustments.Text.Click("72;28");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Text' with focus on 'Cash_Adjustments.Text'.", repo.Cash_Adjustments.TextInfo, new RecordItemIndex(14));
            repo.Cash_Adjustments.Text.PressKeys(Text, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Cash_Adjustments.TotalSpent'.", repo.Cash_Adjustments.TotalSpentInfo, new RecordItemIndex(15));
            Validate.Exists(repo.Cash_Adjustments.TotalSpentInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Cash_Adjustments.TotalSpent' at 40;11.", repo.Cash_Adjustments.TotalSpentInfo, new RecordItemIndex(16));
            repo.Cash_Adjustments.TotalSpent.DoubleClick("40;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Total' with focus on 'Cash_Adjustments.TotalSpent'.", repo.Cash_Adjustments.TotalSpentInfo, new RecordItemIndex(17));
            repo.Cash_Adjustments.TotalSpent.PressKeys(Total, 100);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Cash_Adjustments.TotalSpent'.", repo.Cash_Adjustments.TotalSpentInfo, new RecordItemIndex(18));
            repo.Cash_Adjustments.TotalSpent.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Cash_Adjustments.VATValue'.", repo.Cash_Adjustments.VATValueInfo, new RecordItemIndex(19));
            //Validate.Exists(repo.Cash_Adjustments.VATValueInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Cash_Adjustments.VATValue' at 38;10.", repo.Cash_Adjustments.VATValueInfo, new RecordItemIndex(20));
            //repo.Cash_Adjustments.VATValue.Click("38;10");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Cash_Adjustments.ButtonOK'.", repo.Cash_Adjustments.ButtonOKInfo, new RecordItemIndex(21));
            Validate.Exists(repo.Cash_Adjustments.ButtonOKInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Cash_Adjustments.ButtonOK' at Center.", repo.Cash_Adjustments.ButtonOKInfo, new RecordItemIndex(22));
            repo.Cash_Adjustments.ButtonOK.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrderProcessing.ButtonOK'.", repo.SalesOrderProcessing.ButtonOKInfo, new RecordItemIndex(23));
            Validate.Exists(repo.SalesOrderProcessing.ButtonOKInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SalesOrderProcessing.ButtonOK' at Center.", repo.SalesOrderProcessing.ButtonOKInfo, new RecordItemIndex(24));
            repo.SalesOrderProcessing.ButtonOK.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(25));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
