///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace K8_UK_PP_Regression
{
    public partial class K8MakeCashAdjustmentPP
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void IsOverdrawn()
        {
        	

        	
        	
        	if (repo.OpenCashDrawer.ButtonYesInfo.Exists()) {
        		Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'OpenCashDrawer.ButtonYes'.", repo.OpenCashDrawer.ButtonYesInfo);
	            Validate.Exists(repo.OpenCashDrawer.ButtonYesInfo);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OpenCashDrawer.ButtonYes' at 44;11.", repo.OpenCashDrawer.ButtonYesInfo);
	            repo.OpenCashDrawer.ButtonYes.Click("44;11");
	            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrderProcessing.ButtonOK'.", repo.SalesOrderProcessing.ButtonOKInfo);
	            Validate.Exists(repo.SalesOrderProcessing.ButtonOKInfo);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SalesOrderProcessing.ButtonOK' at 60;9.", repo.SalesOrderProcessing.ButtonOKInfo);
	            repo.SalesOrderProcessing.ButtonOK.Click("60;9");
        	}else{
        		Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrderProcessing.ButtonOK'.", repo.SalesOrderProcessing.ButtonOKInfo);
	            Validate.Exists(repo.SalesOrderProcessing.ButtonOKInfo);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SalesOrderProcessing.ButtonOK' at 60;9.", repo.SalesOrderProcessing.ButtonOKInfo);
	            repo.SalesOrderProcessing.ButtonOK.Click("60;9");
        	}
        	
            
        }
        
        public void NotOverdrawn()
        {
        	if (repo.SalesOrderProcessing.ButtonOK.Visible) {
        		Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrderProcessing.ButtonOK'.", repo.SalesOrderProcessing.ButtonOKInfo);
	            Validate.Exists(repo.SalesOrderProcessing.ButtonOKInfo);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SalesOrderProcessing.ButtonOK' at 60;9.", repo.SalesOrderProcessing.ButtonOKInfo);
	            repo.SalesOrderProcessing.ButtonOK.Click("60;9");
        	}
        }

       

    }
}