///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace K8_UK_PP_Regression
{
    public partial class K8Refund_PP
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void RefundOrderItem1()
        {
        	if (Refund_1.Equals("Y")) {
        		Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.Status2' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.Status2Info);
	            repo.Ql1054K8QA3SalesOrderProcessingD.Status2.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'CRS' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("CRS");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
	            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CreditProductSalesOrder18175.ButtonOK'.", repo.CreditProductSalesOrder18175.ButtonOKInfo);
	            Validate.Exists(repo.CreditProductSalesOrder18175.ButtonOKInfo);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CreditProductSalesOrder18175.ButtonOK' at Center.", repo.CreditProductSalesOrder18175.ButtonOKInfo);
	            repo.CreditProductSalesOrder18175.ButtonOK.Click();
        	}
           
        }

        public void RefundOrderItem2()
        {
        	if (Refund_2.Equals("Y")) {
	        	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.Status3' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.Status3Info);
	            repo.Ql1054K8QA3SalesOrderProcessingD.Status3.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'CRS' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("CRS");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
	            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CreditProductSalesOrder18175.ButtonOK'.", repo.CreditProductSalesOrder18175.ButtonOKInfo);
	            Validate.Exists(repo.CreditProductSalesOrder18175.ButtonOKInfo);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CreditProductSalesOrder18175.ButtonOK' at Center.", repo.CreditProductSalesOrder18175.ButtonOKInfo);
	            repo.CreditProductSalesOrder18175.ButtonOK.Click();
        	}
            
        }

        public void RefundOrderItem3()
        {
        	if (Refund_3.Equals("Y")) {
        		Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.RowRow3.Status' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.RowRow3.StatusInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowRow3.Status.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'CRS' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("CRS");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
	            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CreditProductSalesOrder18175.ButtonOK'.", repo.CreditProductSalesOrder18175.ButtonOKInfo);
	            Validate.Exists(repo.CreditProductSalesOrder18175.ButtonOKInfo);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CreditProductSalesOrder18175.ButtonOK' at Center.", repo.CreditProductSalesOrder18175.ButtonOKInfo);
	            repo.CreditProductSalesOrder18175.ButtonOK.Click();
        	}
            
        }

        public void RefundOrderItem4()
        {
        	if (Refund_4.Equals("Y")) {
	        	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.Status4' at Center.", repo.Ql1054K8QA3SalesOrderProcessingD.Status4Info);
	            repo.Ql1054K8QA3SalesOrderProcessingD.Status4.Click();
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'CRS' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("CRS");
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.RowText'.", repo.Ql1054K8QA3SalesOrderProcessingD.RowTextInfo);
	            repo.Ql1054K8QA3SalesOrderProcessingD.RowText.PressKeys("{Tab}");
	            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CreditProductSalesOrder18175.ButtonOK'.", repo.CreditProductSalesOrder18175.ButtonOKInfo);
	            Validate.Exists(repo.CreditProductSalesOrder18175.ButtonOKInfo);
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CreditProductSalesOrder18175.ButtonOK' at Center.", repo.CreditProductSalesOrder18175.ButtonOKInfo);
	            repo.CreditProductSalesOrder18175.ButtonOK.Click();
        	}

        }

    }
}