///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8Refund_PP recording.
    /// </summary>
    [TestModule("6fab2f06-19b8-46a8-b996-d706c6bdfdd8", ModuleType.Recording, 1)]
    public partial class K8Refund_PP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8Refund_PP instance = new K8Refund_PP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8Refund_PP()
        {
            Refund_1 = "Y";
            Refund_2 = "";
            Refund_3 = "";
            Refund_4 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8Refund_PP Instance
        {
            get { return instance; }
        }

#region Variables

        string _Refund_1;

        /// <summary>
        /// Gets or sets the value of variable Refund_1.
        /// </summary>
        [TestVariable("c9138028-8915-4020-9c74-561848457fd7")]
        public string Refund_1
        {
            get { return _Refund_1; }
            set { _Refund_1 = value; }
        }

        string _Refund_2;

        /// <summary>
        /// Gets or sets the value of variable Refund_2.
        /// </summary>
        [TestVariable("a6e80068-8d4a-45ef-a898-f6075ea768bd")]
        public string Refund_2
        {
            get { return _Refund_2; }
            set { _Refund_2 = value; }
        }

        string _Refund_3;

        /// <summary>
        /// Gets or sets the value of variable Refund_3.
        /// </summary>
        [TestVariable("62ed5df4-0462-4416-aa34-938f0b648d8b")]
        public string Refund_3
        {
            get { return _Refund_3; }
            set { _Refund_3 = value; }
        }

        string _Refund_4;

        /// <summary>
        /// Gets or sets the value of variable Refund_4.
        /// </summary>
        [TestVariable("d4cd82ab-3938-4da0-8b31-1ba899d74447")]
        public string Refund_4
        {
            get { return _Refund_4; }
            set { _Refund_4 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable RefundRow_1.
        /// </summary>
        [TestVariable("6f2b0f85-a393-4081-b3a8-376018dc26ce")]
        public string RefundRow_1
        {
            get { return repo.RefundRow_1; }
            set { repo.RefundRow_1 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable RefundRow_2.
        /// </summary>
        [TestVariable("7ff1d649-078d-4466-b260-50a51c74ac70")]
        public string RefundRow_2
        {
            get { return repo.RefundRow_2; }
            set { repo.RefundRow_2 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable RefundRow_3.
        /// </summary>
        [TestVariable("13e25b04-d544-4cf6-9b1f-a7b25021c5b1")]
        public string RefundRow_3
        {
            get { return repo.RefundRow_3; }
            set { repo.RefundRow_3 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable RefundRow_4.
        /// </summary>
        [TestVariable("8896e7ea-2aab-479a-9f0d-9a3b69a813d5")]
        public string RefundRow_4
        {
            get { return repo.RefundRow_4; }
            set { repo.RefundRow_4 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumberInfo, new RecordItemIndex(0));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumberInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber' at 35;11.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumberInfo, new RecordItemIndex(1));
            repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber.DoubleClick("35;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'L' with focus on 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumberInfo, new RecordItemIndex(2));
            repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber.PressKeys("L", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber2'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber2Info, new RecordItemIndex(3));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber2Info);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Ql1054K8QA3SalesOrderProcessingD.OrderNumber2'.", repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber2Info, new RecordItemIndex(4));
            repo.Ql1054K8QA3SalesOrderProcessingD.OrderNumber2.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            // Refund First Order Line
            Report.Log(ReportLevel.Info, "Section", "Refund First Order Line", new RecordItemIndex(5));
            
            RefundOrderItem1();
            Delay.Milliseconds(0);
            
            // Refund Second Order Line
            Report.Log(ReportLevel.Info, "Section", "Refund Second Order Line", new RecordItemIndex(7));
            
            RefundOrderItem2();
            Delay.Milliseconds(0);
            
            // Refund Third Order Line
            Report.Log(ReportLevel.Info, "Section", "Refund Third Order Line", new RecordItemIndex(9));
            
            RefundOrderItem3();
            Delay.Milliseconds(0);
            
            // Refund Fourth Order Line
            Report.Log(ReportLevel.Info, "Section", "Refund Fourth Order Line", new RecordItemIndex(11));
            
            RefundOrderItem4();
            Delay.Milliseconds(0);
            
            // Process the refund
            Report.Log(ReportLevel.Info, "Section", "Process the refund", new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.Process'.", repo.Ql1054K8QA3SalesOrderProcessingD.ProcessInfo, new RecordItemIndex(14));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.ProcessInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.Process' at 49;22.", repo.Ql1054K8QA3SalesOrderProcessingD.ProcessInfo, new RecordItemIndex(15));
            repo.Ql1054K8QA3SalesOrderProcessingD.Process.Click("49;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ActionSalesOrderSL17707.ButtonOK'.", repo.ActionSalesOrderSL17707.ButtonOKInfo, new RecordItemIndex(16));
            Validate.Exists(repo.ActionSalesOrderSL17707.ButtonOKInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ActionSalesOrderSL17707.ButtonOK' at 24;5.", repo.ActionSalesOrderSL17707.ButtonOKInfo, new RecordItemIndex(17));
            repo.ActionSalesOrderSL17707.ButtonOK.Click("24;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrderProcessingCreditNoteCR.Process'.", repo.SalesOrderProcessingCreditNoteCR.ProcessInfo, new RecordItemIndex(18));
            Validate.Exists(repo.SalesOrderProcessingCreditNoteCR.ProcessInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SalesOrderProcessingCreditNoteCR.Process' at 37;17.", repo.SalesOrderProcessingCreditNoteCR.ProcessInfo, new RecordItemIndex(19));
            repo.SalesOrderProcessingCreditNoteCR.Process.Click("37;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'DeliveryAddress17707D723HowdensW.ButtonOK'.", repo.DeliveryAddress17707D723HowdensW.ButtonOKInfo, new RecordItemIndex(20));
            Validate.Exists(repo.DeliveryAddress17707D723HowdensW.ButtonOKInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeliveryAddress17707D723HowdensW.ButtonOK' at 36;10.", repo.DeliveryAddress17707D723HowdensW.ButtonOKInfo, new RecordItemIndex(21));
            repo.DeliveryAddress17707D723HowdensW.ButtonOK.Click("36;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ActionCreditNoteCR18320.ButtonOK'.", repo.ActionCreditNoteCR18320.ButtonOKInfo, new RecordItemIndex(22));
            Validate.Exists(repo.ActionCreditNoteCR18320.ButtonOKInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ActionCreditNoteCR18320.ButtonOK' at 37;6.", repo.ActionCreditNoteCR18320.ButtonOKInfo, new RecordItemIndex(23));
            repo.ActionCreditNoteCR18320.ButtonOK.Click("37;6");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'DeliveryAddress17707D723HowdensW.ButtonOK'.", repo.DeliveryAddress17707D723HowdensW.ButtonOKInfo, new RecordItemIndex(24));
            //Validate.Exists(repo.DeliveryAddress17707D723HowdensW.ButtonOKInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeliveryAddress17707D723HowdensW.ButtonOK' at Center.", repo.DeliveryAddress17707D723HowdensW.ButtonOKInfo, new RecordItemIndex(25));
            //repo.DeliveryAddress17707D723HowdensW.ButtonOK.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(26));
            Delay.Duration(5000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
