///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8SetDepot_PP recording.
    /// </summary>
    [TestModule("bfdff964-304e-425d-9db0-88603b992a3e", ModuleType.Recording, 1)]
    public partial class K8SetDepot_PP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8SetDepot_PP instance = new K8SetDepot_PP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8SetDepot_PP()
        {
            DepotText = "HJ Enfield";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8SetDepot_PP Instance
        {
            get { return instance; }
        }

#region Variables

        string _DepotText;

        /// <summary>
        /// Gets or sets the value of variable DepotText.
        /// </summary>
        [TestVariable("a474c8ef-9604-4caf-b8a9-864981927b8e")]
        public string DepotText
        {
            get { return _DepotText; }
            set { _DepotText = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1Info, new RecordItemIndex(0));
            Validate.Exists(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1Info, new RecordItemIndex(1));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1Info, new RecordItemIndex(2));
            Keyboard.PrepareFocus(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, 100, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$DepotText' with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1Info, new RecordItemIndex(3));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1.PressKeys(DepotText, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1Info, new RecordItemIndex(4));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Text1.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
