///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8TillTransfer_PP recording.
    /// </summary>
    [TestModule("cfb4d829-c106-45a1-b50a-2f715ee40b79", ModuleType.Recording, 1)]
    public partial class K8TillTransfer_PP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8TillTransfer_PP instance = new K8TillTransfer_PP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8TillTransfer_PP()
        {
            SourceTill = "99";
            DestTill = "1";
            Reference = "Reference";
            TransferValue = "1.00";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8TillTransfer_PP Instance
        {
            get { return instance; }
        }

#region Variables

        string _SourceTill;

        /// <summary>
        /// Gets or sets the value of variable SourceTill.
        /// </summary>
        [TestVariable("1c655704-367e-4101-af50-566b519e7298")]
        public string SourceTill
        {
            get { return _SourceTill; }
            set { _SourceTill = value; }
        }

        string _DestTill;

        /// <summary>
        /// Gets or sets the value of variable DestTill.
        /// </summary>
        [TestVariable("1d4b0813-1750-42db-93b2-28495bc15e1c")]
        public string DestTill
        {
            get { return _DestTill; }
            set { _DestTill = value; }
        }

        string _TransferValue;

        /// <summary>
        /// Gets or sets the value of variable TransferValue.
        /// </summary>
        [TestVariable("0f80a3f4-56a3-4bb5-bfb1-613d8d51afd7")]
        public string TransferValue
        {
            get { return _TransferValue; }
            set { _TransferValue = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Reference.
        /// </summary>
        [TestVariable("461efe05-b729-4b5b-ad1e-757fc253a454")]
        public string Reference
        {
            get { return repo.Reference; }
            set { repo.Reference = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Ql1054K8QA3SalesOrderProcessingD.Tools'.", repo.Ql1054K8QA3SalesOrderProcessingD.ToolsInfo, new RecordItemIndex(0));
            Validate.Exists(repo.Ql1054K8QA3SalesOrderProcessingD.ToolsInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3SalesOrderProcessingD.Tools' at 18;7.", repo.Ql1054K8QA3SalesOrderProcessingD.ToolsInfo, new RecordItemIndex(1));
            repo.Ql1054K8QA3SalesOrderProcessingD.Tools.Click("18;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Kclient.CashAnalysis' at 70;10.", repo.Kclient.CashAnalysisInfo, new RecordItemIndex(2));
            repo.Kclient.CashAnalysis.Click("70;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CashbookCloseATill.ToolBar.TillTransfer'.", repo.CashbookCloseATill.ToolBar.TillTransferInfo, new RecordItemIndex(3));
            Validate.Exists(repo.CashbookCloseATill.ToolBar.TillTransferInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CashbookCloseATill.ToolBar.TillTransfer' at 46;23.", repo.CashbookCloseATill.ToolBar.TillTransferInfo, new RecordItemIndex(4));
            repo.CashbookCloseATill.ToolBar.TillTransfer.Click("46;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'TillCashTransfer.TillNumber'.", repo.TillCashTransfer.TillNumberInfo, new RecordItemIndex(5));
            Validate.Exists(repo.TillCashTransfer.TillNumberInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'TillCashTransfer.TillNumber' at 38;8.", repo.TillCashTransfer.TillNumberInfo, new RecordItemIndex(6));
            repo.TillCashTransfer.TillNumber.DoubleClick("38;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$SourceTill' with focus on 'TillCashTransfer.TillNumber'.", repo.TillCashTransfer.TillNumberInfo, new RecordItemIndex(7));
            repo.TillCashTransfer.TillNumber.PressKeys(SourceTill, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'TillCashTransfer.TillNumber1'.", repo.TillCashTransfer.TillNumber1Info, new RecordItemIndex(8));
            Validate.Exists(repo.TillCashTransfer.TillNumber1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'TillCashTransfer.TillNumber1' at 34;11.", repo.TillCashTransfer.TillNumber1Info, new RecordItemIndex(9));
            repo.TillCashTransfer.TillNumber1.DoubleClick("34;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$DestTill' with focus on 'TillCashTransfer.TillNumber1'.", repo.TillCashTransfer.TillNumber1Info, new RecordItemIndex(10));
            repo.TillCashTransfer.TillNumber1.PressKeys(DestTill, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'TillCashTransfer.Text'.", repo.TillCashTransfer.TextInfo, new RecordItemIndex(11));
            Validate.Exists(repo.TillCashTransfer.TextInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TillCashTransfer.Text' at 54;7.", repo.TillCashTransfer.TextInfo, new RecordItemIndex(12));
            repo.TillCashTransfer.Text.Click("54;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Reference' with focus on 'TillCashTransfer.Text'.", repo.TillCashTransfer.TextInfo, new RecordItemIndex(13));
            repo.TillCashTransfer.Text.PressKeys(Reference, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'TillCashTransfer.TransferValue'.", repo.TillCashTransfer.TransferValueInfo, new RecordItemIndex(14));
            Validate.Exists(repo.TillCashTransfer.TransferValueInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'TillCashTransfer.TransferValue' at 46;11.", repo.TillCashTransfer.TransferValueInfo, new RecordItemIndex(15));
            repo.TillCashTransfer.TransferValue.DoubleClick("46;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TransferValue' with focus on 'TillCashTransfer.TransferValue'.", repo.TillCashTransfer.TransferValueInfo, new RecordItemIndex(16));
            repo.TillCashTransfer.TransferValue.PressKeys(TransferValue, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'TillCashTransfer.TransferValue'.", repo.TillCashTransfer.TransferValueInfo, new RecordItemIndex(17));
            repo.TillCashTransfer.TransferValue.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(18));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'TillCashTransfer.Process'.", repo.TillCashTransfer.ProcessInfo, new RecordItemIndex(19));
            Validate.Exists(repo.TillCashTransfer.ProcessInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TillCashTransfer.Process' at 52;8.", repo.TillCashTransfer.ProcessInfo, new RecordItemIndex(20));
            repo.TillCashTransfer.Process.Click("52;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SalesOrderProcessing.ButtonOK'.", repo.SalesOrderProcessing.ButtonOKInfo, new RecordItemIndex(21));
            Validate.Exists(repo.SalesOrderProcessing.ButtonOKInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SalesOrderProcessing.ButtonOK' at 39;8.", repo.SalesOrderProcessing.ButtonOKInfo, new RecordItemIndex(22));
            repo.SalesOrderProcessing.ButtonOK.Click("39;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CashbookCloseATill.CashTaken' at 86;4.", repo.CashbookCloseATill.CashTakenInfo, new RecordItemIndex(23));
            repo.CashbookCloseATill.CashTaken.Click("86;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'CashbookCloseATill.CashTaken'.", repo.CashbookCloseATill.CashTakenInfo, new RecordItemIndex(24));
            repo.CashbookCloseATill.CashTaken.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CashbookCloseATill.Reference' at 132;10.", repo.CashbookCloseATill.ReferenceInfo, new RecordItemIndex(25));
            repo.CashbookCloseATill.Reference.Click("132;10");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'CashbookCloseATill.Reference'.", repo.CashbookCloseATill.ReferenceInfo, new RecordItemIndex(26));
            //repo.CashbookCloseATill.Reference.PressKeys("{Tab}", 100);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CashbookCloseATill.Quantity' at 23;4.", repo.CashbookCloseATill.QuantityInfo, new RecordItemIndex(27));
            //repo.CashbookCloseATill.Quantity.Click("23;4");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}' with focus on 'CashbookCloseATill.Quantity'.", repo.CashbookCloseATill.QuantityInfo, new RecordItemIndex(28));
            //repo.CashbookCloseATill.Quantity.PressKeys("{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}", 100);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CashAnalysis.ButtonYes'.", repo.CashAnalysis.ButtonYesInfo, new RecordItemIndex(29));
            Validate.Exists(repo.CashAnalysis.ButtonYesInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CashAnalysis.ButtonYes' at 50;13.", repo.CashAnalysis.ButtonYesInfo, new RecordItemIndex(30));
            repo.CashAnalysis.ButtonYes.Click("50;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'UnderOversForCashTaken.Reason'.", repo.UnderOversForCashTaken.ReasonInfo, new RecordItemIndex(31));
            Validate.Exists(repo.UnderOversForCashTaken.ReasonInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UnderOversForCashTaken.Reason' at 74;3.", repo.UnderOversForCashTaken.ReasonInfo, new RecordItemIndex(32));
            repo.UnderOversForCashTaken.Reason.Click("74;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'UnderOversForCashTaken.ButtonOK'.", repo.UnderOversForCashTaken.ButtonOKInfo, new RecordItemIndex(33));
            Validate.Exists(repo.UnderOversForCashTaken.ButtonOKInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UnderOversForCashTaken.ButtonOK' at 38;11.", repo.UnderOversForCashTaken.ButtonOKInfo, new RecordItemIndex(34));
            repo.UnderOversForCashTaken.ButtonOK.Click("38;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CashbookCloseATill.ToolBar.Close'.", repo.CashbookCloseATill.ToolBar.CloseInfo, new RecordItemIndex(35));
            Validate.Exists(repo.CashbookCloseATill.ToolBar.CloseInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CashbookCloseATill.ToolBar.Close' at Center.", repo.CashbookCloseATill.ToolBar.CloseInfo, new RecordItemIndex(36));
            repo.CashbookCloseATill.ToolBar.Close.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CashbookCloseATill.ToolBar.Exit'.", repo.CashbookCloseATill.ToolBar.ExitInfo, new RecordItemIndex(37));
            Validate.Exists(repo.CashbookCloseATill.ToolBar.ExitInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CashbookCloseATill.ToolBar.Exit' at Center.", repo.CashbookCloseATill.ToolBar.ExitInfo, new RecordItemIndex(38));
            repo.CashbookCloseATill.ToolBar.Exit.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
