///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace K8_UK_PP_Regression
{
    public partial class K8ValidateRecord_PP
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void SupersedeWindowExists()
        {
        	if(repo.SupersedeProductsDCK5541.SelfInfo.Exists(1000)){
        		Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='OK') on item 'SupersedeProductsDCK5541.ButtonOK'.", repo.SupersedeProductsDCK5541.ButtonOKInfo);
            	Validate.Attribute(repo.SupersedeProductsDCK5541.ButtonOKInfo, "Text", "OK");
            	
            	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SupersedeProductsDCK5541.ButtonOK' at Center.", repo.SupersedeProductsDCK5541.ButtonOKInfo);
            	repo.SupersedeProductsDCK5541.ButtonOK.Click();
            	
            	Delay.Milliseconds(1000);
            	
            	Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Interrupt') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Interrupt'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.InterruptInfo);
            	Validate.Attribute(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.InterruptInfo, "Text", "Interrupt");
            	
            	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Interrupt' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.InterruptInfo);
            	repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Interrupt.Click();
            	
            	Delay.Milliseconds(2000);
            	
        	}
        	else if(repo.AssociatedProducts.SelfInfo.Exists(1000)){
        		Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='OK') on item 'AssociatedProducts.ButtonOK'.", repo.AssociatedProducts.ButtonOKInfo);
            	Validate.Attribute(repo.AssociatedProducts.ButtonOKInfo, "Text", "OK");
            	
            	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AssociatedProducts.ButtonOK' at Center.", repo.AssociatedProducts.ButtonOKInfo);
            	repo.AssociatedProducts.ButtonOK.Click();
            	
            	Delay.Milliseconds(1000);
            	
            	Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Interrupt') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Interrupt'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.InterruptInfo);
            	Validate.Attribute(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.InterruptInfo, "Text", "Interrupt");
            	
            	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Interrupt' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.InterruptInfo);
            	repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Interrupt.Click();
            	
            	Delay.Milliseconds(2000);
            	
        	}
        	else{
        		Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Interrupt') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Interrupt'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.InterruptInfo);
            	Validate.Attribute(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.InterruptInfo, "Text", "Interrupt");
            	
            	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Interrupt' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.InterruptInfo);
            	repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Interrupt.Click();
            	
            	Delay.Milliseconds(2000);
            	
        	}
            
        }

    }
}