///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace K8_UK_PP_Regression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The K8ViewAccPaymentViaCRM_PP recording.
    /// </summary>
    [TestModule("1bb7b39e-ca8d-4d64-88ef-29aee734da16", ModuleType.Recording, 1)]
    public partial class K8ViewAccPaymentViaCRM_PP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the K8_UK_SOP_RegressionRepository repository.
        /// </summary>
        public static K8_UK_SOP_RegressionRepository repo = K8_UK_SOP_RegressionRepository.Instance;

        static K8ViewAccPaymentViaCRM_PP instance = new K8ViewAccPaymentViaCRM_PP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public K8ViewAccPaymentViaCRM_PP()
        {
            AccNumber = "1000000008";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static K8ViewAccPaymentViaCRM_PP Instance
        {
            get { return instance; }
        }

#region Variables

        string _AccNumber;

        /// <summary>
        /// Gets or sets the value of variable AccNumber.
        /// </summary>
        [TestVariable("f329d046-9a83-42af-997c-0782206f5e53")]
        public string AccNumber
        {
            get { return _AccNumber; }
            set { _AccNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Howdens History') on item 'Ql1054K8QA3BackOfficeUserView2.HowdensHistory'.", repo.Ql1054K8QA3BackOfficeUserView2.HowdensHistoryInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.Ql1054K8QA3BackOfficeUserView2.HowdensHistoryInfo, "Text", "Howdens History");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ql1054K8QA3BackOfficeUserView2.HowdensHistory' at 59;38.", repo.Ql1054K8QA3BackOfficeUserView2.HowdensHistoryInfo, new RecordItemIndex(1));
            repo.Ql1054K8QA3BackOfficeUserView2.HowdensHistory.Click("59;38");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.PushButton1'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.PushButton1Info, new RecordItemIndex(2));
            Validate.Exists(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.PushButton1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.PushButton1' at 14;8.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.PushButton1Info, new RecordItemIndex(3));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.PushButton1.Click("14;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Filter.Between'.", repo.Filter.BetweenInfo, new RecordItemIndex(4));
            Validate.Exists(repo.Filter.BetweenInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Filter.Between' at 24;8.", repo.Filter.BetweenInfo, new RecordItemIndex(5));
            repo.Filter.Between.Click("24;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 't' with focus on 'Filter.Between'.", repo.Filter.BetweenInfo, new RecordItemIndex(6));
            repo.Filter.Between.PressKeys("t", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Filter.And'.", repo.Filter.AndInfo, new RecordItemIndex(7));
            Validate.Exists(repo.Filter.AndInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Filter.And' at 25;10.", repo.Filter.AndInfo, new RecordItemIndex(8));
            repo.Filter.And.Click("25;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 't' with focus on 'Filter.And'.", repo.Filter.AndInfo, new RecordItemIndex(9));
            repo.Filter.And.PressKeys("t", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Filter.Text'.", repo.Filter.TextInfo, new RecordItemIndex(10));
            Validate.Exists(repo.Filter.TextInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Filter.Text' at 41;10.", repo.Filter.TextInfo, new RecordItemIndex(11));
            repo.Filter.Text.Click("41;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AccNumber' with focus on 'Filter.Text'.", repo.Filter.TextInfo, new RecordItemIndex(12));
            repo.Filter.Text.PressKeys(AccNumber, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Filter.Text'.", repo.Filter.TextInfo, new RecordItemIndex(13));
            repo.Filter.Text.PressKeys("{Tab}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='OK') on item 'Filter.ButtonOK'.", repo.Filter.ButtonOKInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.Filter.ButtonOKInfo, "Text", "OK");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Filter.ButtonOK' at 22;9.", repo.Filter.ButtonOKInfo, new RecordItemIndex(15));
            repo.Filter.ButtonOK.Click("22;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.RowRow1'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.RowRow1Info, new RecordItemIndex(16));
            Validate.Exists(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.RowRow1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.RowRow1' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.RowRow1Info, new RecordItemIndex(17));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.RowRow1.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Display Cash Transaction...') on item 'Kclient.DisplayCashTransaction'.", repo.Kclient.DisplayCashTransactionInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.Kclient.DisplayCashTransactionInfo, "Text", "Display Cash Transaction...");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Kclient.DisplayCashTransaction' at 69;13.", repo.Kclient.DisplayCashTransactionInfo, new RecordItemIndex(19));
            repo.Kclient.DisplayCashTransaction.Click("69;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(20));
            Delay.Duration(5000, false);
            
            Report.Screenshot(ReportLevel.Success, "User", "CRM Payment Info", repo.CashTransactionDisplay.Self, false, new RecordItemIndex(21));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Close') on item 'CashTransactionDisplay.Close'.", repo.CashTransactionDisplay.CloseInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.CashTransactionDisplay.CloseInfo, "Text", "Close");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CashTransactionDisplay.Close' at 42;11.", repo.CashTransactionDisplay.CloseInfo, new RecordItemIndex(23));
            repo.CashTransactionDisplay.Close.Click("42;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(24));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Exit') on item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit'.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, new RecordItemIndex(25));
            Validate.AttributeEqual(repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, "Text", "Exit");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit' at Center.", repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.ExitInfo, new RecordItemIndex(26));
            repo.K8UKPPD1Sl1071K8UKPPDHowdensK8HJ0.Exit.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
